import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Jafar | Full Stack Developer",
  description: "Jafar's Full Stack Developer Portfolio. Dedicated, consistent, and Full-Stack in Action.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "java",
    "android",
    "flutter",
    "mern",
    "nodejs",
  ] as Array<string>,
  authors: {
    name: "Jafar Beldar",
    url: "https://github.com",
  },
} as const;
